FIND_PATH(
	SDL2TTF_INCLUDE_DIR
	NAMES SDL_ttf.h
	PATHS /usr/local/include/
)

FIND_PATH(
	SDL2TTF_BINARY_DIRS
	NAMES SDL2_ttf.lib
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	SDL2TTF_LIBRARIES
	NAMES SDL2_ttf.lib
	PATHS /usr/local/lib/
)

IF (SDL2TTF_INCLUDE_DIR AND SDL2TTF_LIBRARIES AND SDL2TTF_BINARY_DIRS)
    SET(SDL2TTF_FOUND TRUE)
ENDIF (SDL2TTF_INCLUDE_DIR AND SDL2TTF_LIBRARIES AND SDL2TTF_BINARY_DIRS)

IF (SDL2TTF_FOUND)
    IF (NOT SDL2TTF_FIND_QUIETLY)
        MESSAGE(STATUS "Found library: ${SDL2TTF_LIBRARIES}")
    ENDIF (NOT SDL2TTF_FIND_QUIETLY)
ELSE (SDL2TTF_FOUND)
    IF (SDL2TTF_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "SDL2_ttf library")
    ENDIF (SDL2TTF_FIND_REQUIRED)
ENDIF (SDL2TTF_FOUND)
